services:
    isotope.listener.console:
        class: Isotope\EventListener\SymlinkCommandListener
        arguments:
            - '%kernel.project_dir%'
        tags:
            - { name: kernel.event_listener, event: console.terminate }

    isotope.listener.frontend_preview:
        class: Isotope\EventListener\FrontendPreviewListener
        tags:
            - { name: kernel.event_listener, event: contao.preview_url_create, method: onPreviewUrlCreate }

    isotope.picker.product:
        class: Isotope\Picker\ProductPickerProvider
        arguments:
            - '@contao.framework'
            - '@knp_menu.factory'
            - '@router'
            - '@translator'
            - '@database_connection'
        tags:
            - contao.picker_provider
